// <auto-generated />
namespace ReWork.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class create_notification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_notification));
        
        string IMigrationMetadata.Id
        {
            get { return "201905151709089_create_notification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
