// <auto-generated />
namespace ReWork.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class change_user1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_user1));
        
        string IMigrationMetadata.Id
        {
            get { return "201904051702153_change_user1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
